### ISSUE TITLE
Research "Better workers" actually makes workers worse

### ISSUE THREAD

**Issue by JbCourtois** [scorzy/IdleAnt2#32]
As of 071cb8bde96bde4510ff79e5aac5f8e86f36d261, the research "Better workers" grants +30% **additive** production per research level, but applies to both gains and losses.

The "additive" part makes this research actually a huge malus when the player also has other additive bonuses, because it will often increase the losses more than the gains.

Suggestions (pick one):
- Make this bonus additive with itself (keep `multiplier = 1 + (0.3 * research_level)`) but compounding with other bonuses
- Make it possible to hide this research in the laboratory, maybe by setting max level = -1

**Comment by scorzy** [comment]
now stack multi
